using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;
using MahApps.Metro.Controls;
using ControlzEx.Theming;
using MahApps.Metro.Controls.Dialogs;
using TurismoNegocio;
using EntidadServicio;

namespace TurismoPresentacion
{
    /// <summary>
    /// Lógica de interacción para MainWindow.xaml
    /// </summary>
    public partial class MainWindow : MetroWindow
    {
        public MainWindow()
        {
            InitializeComponent();
            menu.IsOpen = true;
            swTema.Content = "Oscuro";
            CargarDeptos();
            gridListaDpto.Visibility = Visibility.Hidden;

        }
        private int idDpto = 0;

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            menu.IsOpen = true;
        }

        private void btnGestionDpto_Click(object sender, RoutedEventArgs e)
        {
            Main.Content = null;
            gridListaDpto.Visibility = Visibility.Visible;
            imgFondo.Visibility = Visibility.Hidden;
        }

        private async void btnApagar_Click(object sender, RoutedEventArgs e)
        {
            MessageDialogResult resultado = await this.ShowMessageAsync("Confirmación", "¿Estás seguro que deseas cerrar la aplicación? "
                    , MessageDialogStyle.AffirmativeAndNegative);

            if (resultado == MessageDialogResult.Affirmative)
            {
                Application.Current.Shutdown();
            }
        }


        private void btnUsuarios_Click(object sender, RoutedEventArgs e)
        {
            Main.Content = new AdmUsers();
            imgFondo.Visibility = Visibility.Hidden;
            gridListaDpto.Visibility = Visibility.Hidden;
        }

        private void btnListaUsuarios_Click(object sender, RoutedEventArgs e)
        {
            Main.Content = new AdmDepartamentos(0);
            imgFondo.Visibility = Visibility.Hidden;
            gridListaDpto.Visibility = Visibility.Hidden;
        }



        private void swTema_Toggled(object sender, RoutedEventArgs e)
        {
            //Cambiar tema
            if (swTema.IsOn == true)
            {
                ThemeManager.Current.ChangeTheme(Application.Current, "Dark.Orange");
                swTema.Content = "Normal";

            }
            else
            {
                ThemeManager.Current.ChangeTheme(Application.Current, "Light.Orange");
                swTema.Content = "Oscuro";
            }
        }

        private void btnAbrirInventarios_Click(object sender, RoutedEventArgs e)
        {
            Main.Content = new AdmInventario();
            imgFondo.Visibility = Visibility.Hidden;
            gridListaDpto.Visibility = Visibility.Hidden;
        }


        private void CargarDeptos()
        {
            DepartamentoBl deptos = new DepartamentoBl();
            List<DepartamentoTabla> dptos = deptos.GetDeptos().OrderBy(d => d.id).ToList();
            if (dptos.Count<=0)
            {
                MessageBox.Show("Ha ocurrido un error de red, reintente nuevamente","Error");
            }
            else
            {
                dgDeptos.ItemsSource = null;
                dgDeptos.ItemsSource = dptos;

            }

        }


        private void dgDeptos_AutoGeneratedColumns(object sender, EventArgs e)
        {
            dgDeptos.Columns[0].Header = "Id";
            dgDeptos.Columns[0].DisplayIndex = 0;
            dgDeptos.Columns[1].Header = "Dirección";
            dgDeptos.Columns[1].DisplayIndex = 1;
            dgDeptos.Columns[2].Header = "Dormitorios";
            dgDeptos.Columns[2].DisplayIndex = 2;
            dgDeptos.Columns[3].Header = "Valor arriendo";
            dgDeptos.Columns[3].DisplayIndex = 3;
            dgDeptos.Columns[4].Header = "Baños";
            dgDeptos.Columns[4].DisplayIndex = 4;
            dgDeptos.Columns[5].Header = "Metros²";
            dgDeptos.Columns[5].DisplayIndex = 5;
            dgDeptos.Columns[6].Header = "Estacionamiento";
            dgDeptos.Columns[6].DisplayIndex = 6;
            dgDeptos.Columns[7].Header = "Condiciones";
            dgDeptos.Columns[7].DisplayIndex = 7;
            dgDeptos.Columns[8].Header = "Comuna";
            dgDeptos.Columns[8].DisplayIndex = 8;
            dgDeptos.Columns[9].Header = "id region";
            dgDeptos.Columns[9].DisplayIndex = 9;
            dgDeptos.Columns[9].Visibility = Visibility.Hidden;
            dgDeptos.Columns[10].Header = "Region";
            dgDeptos.Columns[10].DisplayIndex = 10;
            dgDeptos.Columns[11].Header = "Estado";
            dgDeptos.Columns[11].DisplayIndex = 11;
            dgDeptos.Columns[12].Header = "Portada";
            dgDeptos.Columns[12].DisplayIndex = 12;
            dgDeptos.Columns[13].Header = "Content portada";
            dgDeptos.Columns[13].DisplayIndex = 13;
            dgDeptos.Columns[14].Header = "Fecha creación";
            dgDeptos.Columns[14].DisplayIndex = 14;


        }

        private void btnEditarDepto_Click(object sender, RoutedEventArgs e)
        {





            DepartamentoBl deptoBl = new DepartamentoBl();
            List<DepartamentoTabla> dptos = deptoBl.GetDeptos();
            int i = 0;
            if (dgDeptos.SelectedIndex != -1)
            {
                i = dgDeptos.SelectedIndex;

                if (i >= 0)
                {

                    int idDepto;
                    idDepto = (int)dptos[i].id;

                    //Cargar regiones
                    //UbicacionBl ubi = new UbicacionBl();
                    //List<GetComunas> regiones = ubi.GetRegion();
                    //cboRegion1.ItemsSource = regiones;
                    //cboRegion1.SelectedValuePath = "id_region";
                    //cboRegion1.DisplayMemberPath = "nombre_region";

                    //var alo = cboRegion1.SelectedValue;
                    //MessageBox.Show(alo.ToString());

                    //var depto = deptoBl.GetDeptoId(idDepto);

                    Main.Content = new AdmDepartamentos(idDepto);
                    imgFondo.Visibility = Visibility.Hidden;
                    gridListaDpto.Visibility = Visibility.Hidden;

                }
            }
        }

        private void btnCheckIn_Click(object sender, RoutedEventArgs e)
        {
            var selected = dgDeptos.SelectedItem;
            var depto = new DepartamentoTabla();
            if (selected == null)
            {
                MessageBox.Show("Seleccione un departamento en Reserva","Error");
            }
            else
            {
                depto = (DepartamentoTabla)selected;
                if (depto.nombre_estado == "Reserva")
                {
                    UsuarioBl userBl = new UsuarioBl();
                    FlyCheckIn.IsOpen = true;
                    var usuario = userBl.GetUserId(depto.id_usuario).FirstOrDefault();

                }
                else
                {
                    MessageBox.Show("Seleccione un departamento en Reserva", "Error");

                }

            }
        }

        private void Button_Click_1(object sender, RoutedEventArgs e)
        {
            FlyCheckIn.IsOpen = false;
        }

        private void btnCerrarCheckOut_Click(object sender, RoutedEventArgs e)
        {
            FlyCheckOut.IsOpen = false;
        }

        private void btnCheckout_Click(object sender, RoutedEventArgs e)
        {
            FlyCheckOut.IsOpen = true;
        }

        private void Button_Click_2(object sender, RoutedEventArgs e)
        {
            foreach (object o in listBoxCheckout.Items)
                listBoxCheckout.SelectedItems.Add(o);
        }

        private void btnDeactive_Click(object sender, RoutedEventArgs e)
        {
            //Desactivar o activar departamento.

            DepartamentoBl depa = new DepartamentoBl();

            var selected = dgDeptos.SelectedItem;
            var clase = new DepartamentoTabla();

            clase = (DepartamentoTabla)selected;
            decimal Id = clase.id;


            try
            {
                depa.ActivarDepto(91, 3);
            }
            catch (Exception)
            {

                throw;
            }
        }

        private void btnDeactive_Click_1(object sender, RoutedEventArgs e)
        {

        }
    }
}
